//===============================================================
// File:	Primitive.cpp
// Purpose: To Handle Primitive Data
//===============================================================
#include "Primitive.h"
using namespace Graphics::Primitive;

uint32 Topology_DX11_0[eTOPOLOGY_QUANTITY] = 
{
	0,		// eTOPOLOGY_UNDEFINED			D3D_PRIMITIVE_TOPOLOGY_UNDEFINED			= 0,
	1,		// eTOPOLOGY_POINTLIST			D3D_PRIMITIVE_TOPOLOGY_POINTLIST			= 1,
	2,		// eTOPOLOGY_LINELIST			D3D_PRIMITIVE_TOPOLOGY_LINELIST				= 2,
	3,		// eTOPOLOGY_LINESTRIP			D3D_PRIMITIVE_TOPOLOGY_LINESTRIP			= 3,
	4,		// eTOPOLOGY_TRIANGLELIST		D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST			= 4,
	5,		// eTOPOLOGY_TRIANGLESTRIP		D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP		= 5,
	10,		// eTOPOLOGY_LINELIST_ADJ		D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ			= 10,
	11,		// eTOPOLOGY_LINESTRIP_ADJ		D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ		= 11,
	12,		// eTOPOLOGY_TRIANGLELIST_ADJ	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ		= 12,
	13,		// eTOPOLOGY_TRIANGLESTRIP_ADJ	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ	= 13,
};