//===============================================================
// File:	Primitive.h
// Purpose: To Handle Primitive Data
//===============================================================
#pragma once
#include <FTLGraphicsAPI.h>
#include "DirectX.h"

namespace Graphics
{
	namespace Primitive
	{
		const D3D_PRIMITIVE_TOPOLOGY Topology_DX11_0[eTOPOLOGY_QUANTITY] = 
		{
			D3D_PRIMITIVE_TOPOLOGY_UNDEFINED,			// eTOPOLOGY_UNDEFINED
			D3D_PRIMITIVE_TOPOLOGY_POINTLIST,			// eTOPOLOGY_POINTLIST
			D3D_PRIMITIVE_TOPOLOGY_LINELIST,			// eTOPOLOGY_LINELIST
			D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,			// eTOPOLOGY_LINESTRIP
			D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,		// eTOPOLOGY_TRIANGLELIST
			D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,		// eTOPOLOGY_TRIANGLESTRIP
			D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,		// eTOPOLOGY_LINELIST_ADJ
			D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,		// eTOPOLOGY_LINESTRIP_ADJ
			D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,	// eTOPOLOGY_TRIANGLELIST_ADJ
			D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,	// eTOPOLOGY_TRIANGLESTRIP_ADJ
		};

	}
}

